"""make password_hash not null

Revision ID: 482dac4a4498
Revises: 202c3b04b4e8
Create Date: 2026-03-02 21:01:43.099089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482dac4a4498'
down_revision = '202c3b04b4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)

    # ### end Alembic commands ###
